/*

package com.example.friendsList.domain.entity;

public interface AutoGeneratedIdManageable {

    String getAutoGeneratedId();

    void setAutoGeneratedId(String id);
}

//自動生成するデータにこのインターフェイスをimplementする


 */
