INSERT INTO friends VALUES (null, '山田太郎', '19900505', 'カレー', '犬', 'よろしくお願いします！！！');
INSERT INTO friends VALUES (null, '鈴木一郎', '19981122', 'かつ丼', '猫', 'ヤッホー！！！！！！！！！！！！');
INSERT INTO friends VALUES (null, '佐藤二朗', '19890321', '肉じゃが', 'チンチラ', '役者やってます！');
INSERT INTO friends VALUES (null, '安倍晋三', '15450903', 'パエリア', 'インコ', 'アベノミクスどうでした？');
INSERT INTO friends VALUES (null, 'ポール・マッカートニー', '18990707', 'サイ', '犬', '実はパンク好きです');
INSERT INTO friends VALUES (null, '香川真司', '19780825', 'うどん', 'トラ', '日本帰りたい');
INSERT INTO friends VALUES (null, '本田圭佑', '19770416', '餅', 'カピバラ', 'リトルホンダ！');
INSERT INTO friends VALUES (null, '大谷翔平', '19601225', 'ハンバーガー', 'うさぎ', 'サッカー大好き');
INSERT INTO friends VALUES (null, '小池百合子', '20050301', '寿司', 'チンパンジー', '田舎に住みたい！');
INSERT INTO friends VALUES (null, 'マイケル・ジャクソン', '20120417', '天津飯', 'ワニ', 'This is it');